version: '3.9'

services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: laflait
      MYSQL_USER: user
      MYSQL_PASSWORD: heslo
      MYSQL_ROOT_PASSWORD: heslo
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
